export const LOAD_ARTIST = 'LOAD_ARTIST';
export const LOAD_ARTIST_REQUEST = 'LOAD_ARTIST_REQUEST';
export const LOAD_ARTIST_EVENTS = 'LOAD_ARTIST_EVENTS';
export const LOAD_ARTIST_EVENTS_REQUEST = 'LOAD_ARTIST_EVENTS_REQUEST';

